version: '3.8'

services:
  web:
    build: .
    container_name: php-apache
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:12
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: labreferencial_cpe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init/labrefcpe.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  jenkins:
    container_name: jenkins
    build:
      context: .  # Usamos el contexto de la raíz del proyecto
      dockerfile: Dockerfile  # El Dockerfile está en la raíz del proyecto
    volumes:
      - ./jenkins_home:/var/jenkins_home  # Ruta para Linux
      - /var/run/docker.sock:/var/run/docker.sock  # Acceso a Docker desde el contenedor
    ports:
      - "9080:8080"  # Puerto de Jenkins en tu servidor (9080) hacia el contenedor (8080)
    networks:
      - app-network
    restart: unless-stopped

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
